doctrine_mongodb:
  connections:
    default:
      server: '%env(resolve:MONGODB_URL)%'
      options: {}
  default_database: '%env(MONGODB_DB)%'
  document_managers:
    default:
      auto_mapping: false
      mappings:
        App:
          is_bundle: false
          type: attribute        # <- ici, pas annotation, mais attribute
          dir: '%kernel.project_dir%/src/Document'
          prefix: 'App\Document'
          alias: App
