# config/services.yaml

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'         # pas nécessaire mais tu peux l’enlever si tu n'utilises pas Doctrine ORM
            - '../src/Kernel.php'

    # Exemple de définition explicite (à adapter selon ton code)
    # Ici, si tu as un UserProvider personnalisé (optionnel)
    # App\Security\MongoUserProvider:
    #     arguments:
    #         $dm: '@doctrine_mongodb.odm.document_manager'
